name: leaflearn
description: "LeafLearn, the green and sustainable learning platform!"
# private package
publish_to: 'none'
version: 0.0.1+1
environment:
  sdk: '>=3.2.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  go_router: ^13.0.1
  provider: ^6.1.1
  http: ^1.2.0
  flutter_secure_storage: ^9.0.0
  flutter_dotenv: ^5.1.0
  flutter_markdown: ^0.6.20
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.13.1"
  go_router_builder: ^2.4.1
  build_runner: ^2.4.8
  build_verify: ^3.1.0
flutter:
  uses-material-design: true
  assets:
      - courses/
      - images/logo.png
      - images/burger.jpeg
      - .env
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    background_color: "#000000"
    theme_color: "#000000"
  windows:
    generate: true
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
  linux:
    generate: true
    

